---
title: "SpawningAnalysis"
author: "Matilde Correia"
date: "2024-07-04"
output: html_document
---

```{r}
if(!require(correlation)){install.packages("correlation"); library(correlation)}
if(!require(car)){install.packages("car"); library(car)}
if(!require(mgcv)){install.packages("mgcv"); library(mgcv)}
if(!require(rpart)){install.packages("rpart"); library(rpart)}
if(!require(ggplot2)){install.packages("ggplot2"); library(ggplot2)}
if(!require(gridExtra)){install.packages("gridExtra"); library(gridExtra)}
if(!require(lme4)){install.packages("lme4"); library(lme4)}
if(!require(Matrix)){install.packages("Matrix"); library(Matrix)}
if(!require(lmtest)){install.packages("lmtest"); library(lmtest)}
if(!require(gamm4)){install.packages("gamm4"); library(gamm4)}
if(!require(sjPlot)){install.packages("sjPlot"); library(sjPlot)}
if(!require(sjmisc)){install.packages("sjmisc"); library(sjmisc)}
if(!require(sjlabelled)){install.packages("sjlabelled"); library(sjlabelled)}
if(!require(performance)){install.packages("performance"); library(performance)}
if(!require(glmmTMB)){install.packages("glmmTMB"); library(glmmTMB)}
if(!require(DHARMa)){install.packages("DHARMa"); library(DHARMa)}
```


### Import Dataset

```{r}
#Import data
week_kuds <- read.csv("week_kuds2.2.csv", sep=";") #has the wrong week values
week_kuds3 <- read.csv("week_kuds1 - usar.csv", sep=";") #has the right week values
week_kuds$Week <- week_kuds3$Week #substitute the wrong for the right week in the dataset
#create week variable without the year
names(week_kuds)[names(week_kuds) == "Week"] <- "WeekYear"
week_kuds$Week <- substr(week_kuds$WeekYear, 1, 2)
#create year variable without the week
week_kuds$Year <- substr(week_kuds$WeekYear, 4, 7)

week_kuds$File <- as.factor(week_kuds$File)
week_kuds$Species <- as.factor(week_kuds$Species)
week_kuds$Transmitter <- as.factor(week_kuds$Transmitter)
week_kuds$KUD50 <- as.numeric(week_kuds$KUD50)
week_kuds$KUD95 <- as.numeric(week_kuds$KUD95)
week_kuds$Habitat <- as.factor(week_kuds$Habitat)
week_kuds$Migration <- as.factor(week_kuds$Migration)
week_kuds$ComImport <- as.factor(week_kuds$ComImport)
week_kuds$Length_cm <- as.numeric(week_kuds$Length_cm)
week_kuds$LengthStd <- as.numeric(week_kuds$LengthStd)
week_kuds$BodyMass <- as.numeric(week_kuds$BodyMass)
week_kuds$BodyMassStd <- as.numeric(week_kuds$BodyMassStd)
week_kuds$Longevity <- as.numeric(week_kuds$Longevity)
week_kuds$Vulnerability <- as.numeric(week_kuds$Vulnerability)
week_kuds$Troph <- as.numeric(week_kuds$Troph)
week_kuds$ReceiverDensity <- as.numeric(week_kuds$ReceiverDensity)
week_kuds$MonitArea_km2 <- as.numeric(week_kuds$MonitArea_km2)
week_kuds$MCP_km2 <- as.numeric(week_kuds$MCP_km2)
week_kuds$NReceivers <- as.numeric(week_kuds$NReceivers)
week_kuds$MaxDistReceivers <- as.numeric(week_kuds$MaxDistReceivers)
week_kuds$MaxLength <- as.numeric(week_kuds$MaxLength)
week_kuds$MaxBodyMass <- as.numeric(week_kuds$MaxBodyMass)
week_kuds$a <- as.numeric(week_kuds$a)
week_kuds$b <- as.numeric(week_kuds$b)
week_kuds$Week <- as.factor(week_kuds$Week)
week_kuds$Year <- as.factor(week_kuds$Year)
week_kuds$Spawn <- as.factor(week_kuds$Spawn)

week_kuds$Spawn <- with(week_kuds, ifelse((SpawnSeason == "SS" & Week %in% c("11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40")) |
                          (SpawnSeason == "A" & Week %in% c("41", "42", "43", "44", "45", "46", "47", "48", "49", "50")) |
                          (SpawnSeason == "W" & Week %in% c("51", "52", "53", "54", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10")),
                          "yes", "no"))
week_kuds$SpawnSeason <- as.factor(week_kuds$SpawnSeason)
```


```{r}
boxplot(KUD95 ~ Spawn, data= week_kuds, col="deepskyblue")

boxplot(KUD50 ~ Spawn, data= week_kuds, col="green2")

#Comparar as médias dos KUDs dos individuos que se encontravam em época reprodutiva ou não

#escolhemos o teste wilcox porque não assume normalidade nos dados e é útil para grandes e pequenas amostras
wilcox.test(week_kuds$KUD95~week_kuds$Spawn)  #de acordo com o teste realizado parece não haver evidências para afirmar que a home range varia consoante a Epoca Reprodutiva, visto que o p-value toma o valor de 0.5623 que é maior do que o nivel de significância 0.05

wilcox.test(week_kuds$KUD50~week_kuds$Spawn) #de acordo com o teste realizado parece não haver evidências para afirmar que a core area varia consoante a Epoca Reprodutiva, visto que o p-value toma o valor de 0.9972 que é maior do que o nivel de significância 0.05

glmm_total_kud95 <- glmmTMB(KUD95 ~ Spawn + MonitArea_km2 + (1|Species) + (1|Transmitter), data=week_kuds, family = Gamma(link="log"))
summary(glmm_total_kud95)


glmm_total_kud50 <- glmmTMB(KUD50 ~ Spawn + MonitArea_km2 + (1|Species) + (1|Transmitter), data=week_kuds, family = Gamma(link="log"))
summary(glmm_total_kud50)

#Analisys by File
# Divide dataset by 'File'
split_spawnFile <- split(week_kuds, week_kuds$File)

# Function to use the wilcoxon test in each sub-dataframe
wilcox_test_kud95 <- function(data) {
  # Verify if Spawn has exactly 2 levels (yes and no)
  if(length(unique(data$Spawn)) == 2) {
    test_result <- wilcox.test(KUD95 ~ Spawn, data = data)
    return(test_result$p.value)
  } else {
    return(NA)  # Return NA if not
  }
}

# Apply the function and get the p-values
p_values <- lapply(split_spawnFile, wilcox_test_kud95)

# Exhibit p-values
print(p_values)

p_values<- t(as.data.frame(p_values))

# Function to use the wilcoxon test in each sub-dataframe
wilcox_test_kud50 <- function(data) {
  # Verify if Spawn has exactly 2 levels (yes and no)
  if(length(unique(data$Spawn)) == 2) {
    test_result <- wilcox.test(KUD50 ~ Spawn, data = data)
    return(test_result$p.value)
  } else {
    return(NA)  # Return NA if not
  }
}

# Apply the function and get the p-values
p_values <- lapply(split_spawnFile, wilcox_test_kud50)

# Exhibit p-values
print(p_values)

p_values<- t(as.data.frame(p_values))


```


```{r}
#Glmm KUD95 for each File

data_dentex_dentex1 <- subset(week_kuds, File == "Dentex_dentex1")

glmm_dentex_dentex1 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_dentex_dentex1, family = Gamma(link="log"))
summary(glmm_dentex_dentex1)

boxplot(data_dentex_dentex1$KUD95 ~ data_dentex_dentex1$Spawn)
#################################################################################
data_dentex_dentex2 <- subset(week_kuds, File == "Dentex_dentex2")

glmm_dentex_dentex2 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_dentex_dentex2, family = Gamma(link="log"))
summary(glmm_dentex_dentex2)

boxplot(data_dentex_dentex2$KUD95 ~ data_dentex_dentex2$Spawn)
#################################################################################
data_dicentrarchus_labrax1 <- subset(week_kuds, File == "Dicentrarchus_labrax1")

glmm_dicentrarchus_labrax1 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_dicentrarchus_labrax1, family = Gamma(link="log"))
summary(glmm_dicentrarchus_labrax1)

boxplot(data_dicentrarchus_labrax1$KUD95 ~ data_dicentrarchus_labrax1$Spawn)
#################################################################################
data_dicentrarchus_labrax2 <- subset(week_kuds, File == "Dicentrarchus_labrax2")

glmm_dicentrarchus_labrax2 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_dicentrarchus_labrax2, family = Gamma(link="log"))
summary(glmm_dicentrarchus_labrax2)

boxplot(data_dicentrarchus_labrax2$KUD95 ~ data_dicentrarchus_labrax2$Spawn)
#################################################################################
data_diplodus_cervinus <- subset(week_kuds, File == "Diplodus_cervinus")

glmm_diplodus_cervinus <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_diplodus_cervinus, family = Gamma(link="log"))
summary(glmm_diplodus_cervinus)

boxplot(data_diplodus_cervinus$KUD95 ~ data_diplodus_cervinus$Spawn)
#################################################################################
data_diplodus_sargus1 <- subset(week_kuds, File == "Diplodus_sargus1")

glmm_diplodus_sargus1 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_diplodus_sargus1, family = Gamma(link="log"))
summary(glmm_diplodus_sargus1)

boxplot(data_diplodus_sargus1$KUD95 ~ data_diplodus_sargus1$Spawn)
#################################################################################
data_diplodus_sargus2 <- subset(week_kuds, File == "Diplodus_sargus2")

glmm_diplodus_sargus2 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_diplodus_sargus2, family = Gamma(link="log"))
summary(glmm_diplodus_sargus2)

boxplot(data_diplodus_sargus2$KUD95 ~ data_diplodus_sargus2$Spawn)
#################################################################################
data_diplodus_sargus3 <- subset(week_kuds, File == "Diplodus_sargus3")

glmm_diplodus_sargus3 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_diplodus_sargus3, family = Gamma(link="log"))
summary(glmm_diplodus_sargus3)

boxplot(data_diplodus_sargus3$KUD95 ~ data_diplodus_sargus3$Spawn)
#################################################################################
data_diplodus_sargus4 <- subset(week_kuds, File == "Diplodus_sargus4")

glmm_diplodus_sargus4 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_diplodus_sargus4, family = Gamma(link="log"))
summary(glmm_diplodus_sargus4)

boxplot(data_diplodus_sargus4$KUD95 ~ data_diplodus_sargus4$Spawn)
#################################################################################
data_diplodus_sargus5 <- subset(week_kuds, File == "Diplodus_sargus5")

glmm_diplodus_sargus5 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_diplodus_sargus5, family = Gamma(link="log"))
summary(glmm_diplodus_sargus5)

boxplot(data_diplodus_sargus5$KUD95 ~ data_diplodus_sargus5$Spawn)
#################################################################################
data_diplodus_sargus6 <- subset(week_kuds, File == "Diplodus_sargus6")

glmm_diplodus_sargus6 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_diplodus_sargus6, family = Gamma(link="log"))
summary(glmm_diplodus_sargus6)

boxplot(data_diplodus_sargus6$KUD95 ~ data_diplodus_sargus6$Spawn)
#################################################################################
data_diplodus_vulgaris1 <- subset(week_kuds, File == "Diplodus_vulgaris1")

glmm_diplodus_vulgaris1 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_diplodus_vulgaris1, family = Gamma(link="log"))
summary(glmm_diplodus_vulgaris1)

boxplot(data_diplodus_vulgaris1$KUD95 ~ data_diplodus_vulgaris1$Spawn)
#################################################################################
data_diplodus_vulgaris2 <- subset(week_kuds, File == "Diplodus_vulgaris2")

glmm_diplodus_vulgaris2 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_diplodus_vulgaris2, family = Gamma(link="log"))
summary(glmm_diplodus_vulgaris2)

boxplot(data_diplodus_vulgaris2$KUD95 ~ data_diplodus_vulgaris2$Spawn)
#################################################################################
data_epinephelus_marginatus1 <- subset(week_kuds, File == "Epinephelus_marginatus1")

glmm_epinephelus_marginatus1 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_epinephelus_marginatus1, family = Gamma(link="log"))
summary(glmm_epinephelus_marginatus1)

boxplot(data_epinephelus_marginatus1$KUD95 ~ data_epinephelus_marginatus1$Spawn)
#################################################################################
data_epinephelus_marginatus2 <- subset(week_kuds, File == "Epinephelus_marginatus2")

glmm_epinephelus_marginatus2 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_epinephelus_marginatus2, family = Gamma(link="log"))
summary(glmm_epinephelus_marginatus2)

boxplot(data_epinephelus_marginatus2$KUD95 ~ data_epinephelus_marginatus2$Spawn)
#################################################################################
data_epinephelus_marginatus3 <- subset(week_kuds, File == "Epinephelus_marginatus3")

glmm_epinephelus_marginatus3 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_epinephelus_marginatus3, family = Gamma(link="log"))
summary(glmm_epinephelus_marginatus3)

boxplot(data_epinephelus_marginatus3$KUD95 ~ data_epinephelus_marginatus3$Spawn)
#################################################################################
data_epinephelus_marginatus4 <- subset(week_kuds, File == "Epinephelus_marginatus4")

glmm_epinephelus_marginatus4 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_epinephelus_marginatus4, family = Gamma(link="log"))
summary(glmm_epinephelus_marginatus4)

boxplot(data_epinephelus_marginatus4$KUD95 ~ data_epinephelus_marginatus4$Spawn)
#################################################################################
data_gadus_morhua1 <- subset(week_kuds, File == "Gadus_morhua1")

glmm_gadus_morhua1 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_gadus_morhua1, family = Gamma(link="log"))
summary(glmm_gadus_morhua1)

boxplot(data_gadus_morhua1$KUD95 ~ data_gadus_morhua1$Spawn)
#################################################################################
data_gadus_morhua2 <- subset(week_kuds, File == "Gadus_morhua2")

glmm_gadus_morhua2 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_gadus_morhua2, family = Gamma(link="log"))
summary(glmm_gadus_morhua2)

boxplot(data_gadus_morhua2$KUD95 ~ data_gadus_morhua2$Spawn)
#################################################################################
data_gadus_morhua3 <- subset(week_kuds, File == "Gadus_morhua3")

glmm_gadus_morhua3 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_gadus_morhua3, family = Gamma(link="log"))
summary(glmm_gadus_morhua3)

boxplot(data_gadus_morhua3$KUD95 ~ data_gadus_morhua3$Spawn)
#################################################################################
data_labrus_bergylta <- subset(week_kuds, File == "Labrus_bergylta")

glmm_labrus_bergylta <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_labrus_bergylta, family = Gamma(link="log"))
summary(glmm_labrus_bergylta)

boxplot(data_labrus_bergylta$KUD95 ~ data_labrus_bergylta$Spawn)
#################################################################################
data_lichia_amia<- subset(week_kuds, File == "Lichia_amia")

glmm_lichia_amia <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_lichia_amia, family = Gamma(link="log"))
summary(glmm_lichia_amia)

boxplot(data_lichia_amia$KUD95 ~ data_lichia_amia$Spawn)
#################################################################################
data_pagrus_pagrus1 <- subset(week_kuds, File == "Pagrus_pagrus1")

glmm_pagrus_pagrus1 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_pagrus_pagrus1, family = Gamma(link="log"))
summary(glmm_pagrus_pagrus1)

boxplot(data_pagrus_pagrus1$KUD95 ~ data_pagrus_pagrus1$Spawn)
#################################################################################
data_pagrus_pagrus2 <- subset(week_kuds, File == "Pagrus_pagrus2")

glmm_pagrus_pagrus2 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_pagrus_pagrus2, family = Gamma(link="log"))
summary(glmm_pagrus_pagrus2)

boxplot(data_pagrus_pagrus2$KUD95 ~ data_pagrus_pagrus2$Spawn)
#################################################################################
data_pomatomus_saltatrix <- subset(week_kuds, File == "Pomatomus_saltatrix")

glmm_pomatomus_saltatrix <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_pomatomus_saltatrix, family = Gamma(link="log"))
summary(glmm_pomatomus_saltatrix)

boxplot(data_pomatomus_saltatrix$KUD95 ~ data_pomatomus_saltatrix$Spawn)
#################################################################################
data_pseudocaranx_dentex <- subset(week_kuds, File == "Pseudocaranx_dentex")

glmm_pseudocaranx_dentex <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_pseudocaranx_dentex, family = Gamma(link="log"))
summary(glmm_pseudocaranx_dentex)

boxplot(data_pseudocaranx_dentex$KUD95 ~ data_pseudocaranx_dentex$Spawn)
#################################################################################
data_sciaena_umbra1 <- subset(week_kuds, File == "Sciaena_umbra1")

glmm_sciaena_umbra1 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_sciaena_umbra1, family = Gamma(link="log"))
summary(glmm_sciaena_umbra1)

boxplot(data_sciaena_umbra1$KUD95 ~ data_sciaena_umbra1$Spawn)
#################################################################################
data_sciaena_umbra2 <- subset(week_kuds, File == "Sciaena_umbra2")

glmm_sciaena_umbra2 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_sciaena_umbra2, family = Gamma(link="log"))
summary(glmm_sciaena_umbra2)

boxplot(data_sciaena_umbra2$KUD95 ~ data_sciaena_umbra2$Spawn)
#################################################################################
data_scorpaena_porcus <- subset(week_kuds, File == "Scorpaena_porcus")

glmm_scorpaena_porcus <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_scorpaena_porcus, family = Gamma(link="log"))
summary(glmm_scorpaena_porcus)

boxplot(data_scorpaena_porcus$KUD95 ~ data_scorpaena_porcus$Spawn)
#################################################################################
data_scorpaena_scrofa1 <- subset(week_kuds, File == "Scorpaena_scrofa1")

glmm_scorpaena_scrofa1 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_scorpaena_scrofa1, family = Gamma(link="log"))
summary(glmm_scorpaena_scrofa1)

boxplot(data_scorpaena_scrofa1$KUD95 ~ data_scorpaena_scrofa1$Spawn)
#################################################################################
data_scorpaena_scrofa2 <- subset(week_kuds, File == "Scorpaena_scrofa2")

glmm_scorpaena_scrofa2 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_scorpaena_scrofa2, family = Gamma(link="log"))
summary(glmm_scorpaena_scrofa2)

boxplot(data_scorpaena_scrofa2$KUD95 ~ data_scorpaena_scrofa2$Spawn)
#################################################################################
data_seriola_dumerili <- subset(week_kuds, File == "Seriola_dumerili")

glmm_seriola_dumerili <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_seriola_dumerili, family = Gamma(link="log"))
summary(glmm_seriola_dumerili)

boxplot(data_seriola_dumerili$KUD95 ~ data_seriola_dumerili$Spawn)
#################################################################################
data_seriola_rivoliana <- subset(week_kuds, File == "Seriola_rivoliana")

glmm_seriola_rivoliana <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_seriola_rivoliana, family = Gamma(link="log"))
summary(glmm_seriola_rivoliana)

boxplot(data_seriola_rivoliana$KUD95 ~ data_seriola_rivoliana$Spawn)
#################################################################################
data_serranus_atricauda <- subset(week_kuds, File == "Serranus_atricauda")

glmm_serranus_atricauda <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_serranus_atricauda, family = Gamma(link="log"))
summary(glmm_serranus_atricauda)

boxplot(data_serranus_atricauda$KUD95 ~ data_serranus_atricauda$Spawn)
#################################################################################
data_serranus_scriba <- subset(week_kuds, File == "Serranus_scriba")

glmm_serranus_scriba <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_serranus_scriba, family = Gamma(link="log"))
summary(glmm_serranus_scriba)

boxplot(data_serranus_scriba$KUD95 ~ data_serranus_scriba$Spawn)
#################################################################################
data_solea_senegalensis <- subset(week_kuds, File == "Solea_senegalensis")

glmm_solea_senegalensis <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_solea_senegalensis, family = Gamma(link="log"))
summary(glmm_solea_senegalensis)

boxplot(data_solea_senegalensis$KUD95 ~ data_solea_senegalensis$Spawn)
#################################################################################
data_sparisoma_cretense <- subset(week_kuds, File == "Sparisoma_cretense")

glmm_sparisoma_cretense <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_sparisoma_cretense, family = Gamma(link="log"))
summary(glmm_sparisoma_cretense)

boxplot(data_sparisoma_cretense$KUD95 ~ data_sparisoma_cretense$Spawn)
#################################################################################
data_sparus_aurata1 <- subset(week_kuds, File == "Sparus_aurata1")

glmm_sparus_aurata1 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_sparus_aurata1, family = Gamma(link="log"))
summary(glmm_sparus_aurata1)

boxplot(data_sparus_aurata1$KUD95 ~ data_sparus_aurata1$Spawn)
#################################################################################
data_sparus_aurata2 <- subset(week_kuds, File == "Sparus_aurata2")

glmm_sparus_aurata2 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_sparus_aurata2, family = Gamma(link="log"))
summary(glmm_sparus_aurata2)

boxplot(data_sparus_aurata2$KUD95 ~ data_sparus_aurata2$Spawn)
#################################################################################
data_sphyraena_viridensis1 <- subset(week_kuds, File == "Sphyraena_viridensis1")

glmm_sphyraena_viridensis1 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_sphyraena_viridensis1, family = Gamma(link="log"))
summary(glmm_sphyraena_viridensis1)

boxplot(data_sphyraena_viridensis1$KUD95 ~ data_sphyraena_viridensis1$Spawn)
#################################################################################
data_sphyraena_viridensis2 <- subset(week_kuds, File == "Sphyraena_viridensis2")

glmm_sphyraena_viridensis2 <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_sphyraena_viridensis2, family = Gamma(link="log"))
summary(glmm_sphyraena_viridensis2)

boxplot(data_sphyraena_viridensis2$KUD95 ~ data_sphyraena_viridensis2$Spawn)
#################################################################################
data_spondyliosoma_cantharus <- subset(week_kuds, File == "Spondyliosoma_cantharus")

glmm_spondyliosoma_cantharus <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_spondyliosoma_cantharus, family = Gamma(link="log"))
summary(glmm_spondyliosoma_cantharus)

boxplot(data_spondyliosoma_cantharus$KUD95 ~ data_spondyliosoma_cantharus$Spawn)
#################################################################################
```

```{r}
#Glmm KUD95 for each Species

data_dentex_dentex <- subset(week_kuds, Species == "Dden")

glmm_dentex_dentex <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_dentex_dentex, family = Gamma(link="log"))
summary(glmm_dentex_dentex)

boxplot(data_dentex_dentex$KUD95 ~ data_dentex_dentex$Spawn)
#################################################################################
data_dicentrarchus_labrax <- subset(week_kuds, Species == "Dlab")

glmm_dicentrarchus_labrax <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_dicentrarchus_labrax, family = Gamma(link="log"))
summary(glmm_dicentrarchus_labrax)

boxplot(data_dicentrarchus_labrax$KUD95 ~ data_dicentrarchus_labrax$Spawn)
#################################################################################
data_diplodus_cervinus <- subset(week_kuds, Species == "Dcer")

glmm_diplodus_cervinus <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_diplodus_cervinus, family = Gamma(link="log"))
summary(glmm_diplodus_cervinus)

boxplot(data_diplodus_cervinus$KUD95 ~ data_diplodus_cervinus$Spawn)
#################################################################################
data_diplodus_sargus <- subset(week_kuds, Species == "Dsar")

glmm_diplodus_sargus <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_diplodus_sargus, family = Gamma(link="log"))
summary(glmm_diplodus_sargus)

boxplot(data_diplodus_sargus$KUD95 ~ data_diplodus_sargus$Spawn)
#################################################################################
data_diplodus_vulgaris <- subset(week_kuds, Species == "Dvul")

glmm_diplodus_vulgaris <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_diplodus_vulgaris, family = Gamma(link="log"))
summary(glmm_diplodus_vulgaris)

boxplot(data_diplodus_vulgaris$KUD95 ~ data_diplodus_vulgaris$Spawn)
#################################################################################
data_epinephelus_marginatus <- subset(week_kuds, Species == "Emar")

glmm_epinephelus_marginatus <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_epinephelus_marginatus, family = Gamma(link="log"))
summary(glmm_epinephelus_marginatus)

boxplot(data_epinephelus_marginatus$KUD95 ~ data_epinephelus_marginatus$Spawn)
#################################################################################
data_gadus_morhua <- subset(week_kuds, Species == "Gmor")

glmm_gadus_morhua <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_gadus_morhua, family = Gamma(link="log"))
summary(glmm_gadus_morhua)

boxplot(data_gadus_morhua$KUD95 ~ data_gadus_morhua$Spawn)
#################################################################################
data_labrus_bergylta <- subset(week_kuds, Species == "Lber")

glmm_labrus_bergylta <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_labrus_bergylta, family = Gamma(link="log"))
summary(glmm_labrus_bergylta)

boxplot(data_labrus_bergylta$KUD95 ~ data_labrus_bergylta$Spawn)
#################################################################################
data_lichia_amia<- subset(week_kuds, Species == "Lami")

glmm_lichia_amia <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_lichia_amia, family = Gamma(link="log"))
summary(glmm_lichia_amia)

boxplot(data_lichia_amia$KUD95 ~ data_lichia_amia$Spawn)
#################################################################################
data_pagrus_pagrus <- subset(week_kuds, Species == "Ppag")

glmm_pagrus_pagrus <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_pagrus_pagrus, family = Gamma(link="log"))
summary(glmm_pagrus_pagrus)

boxplot(data_pagrus_pagrus$KUD95 ~ data_pagrus_pagrus$Spawn)
#################################################################################
data_pomatomus_saltatrix <- subset(week_kuds, Species == "Psal")

glmm_pomatomus_saltatrix <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_pomatomus_saltatrix, family = Gamma(link="log"))
summary(glmm_pomatomus_saltatrix)

boxplot(data_pomatomus_saltatrix$KUD95 ~ data_pomatomus_saltatrix$Spawn)
#################################################################################
data_pseudocaranx_dentex <- subset(week_kuds, Species == "Pden")

glmm_pseudocaranx_dentex <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_pseudocaranx_dentex, family = Gamma(link="log"))
summary(glmm_pseudocaranx_dentex)

boxplot(data_pseudocaranx_dentex$KUD95 ~ data_pseudocaranx_dentex$Spawn)
#################################################################################
data_sciaena_umbra <- subset(week_kuds, Species == "Sumb")

glmm_sciaena_umbra <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_sciaena_umbra, family = Gamma(link="log"))
summary(glmm_sciaena_umbra)

boxplot(data_sciaena_umbra$KUD95 ~ data_sciaena_umbra$Spawn)
#################################################################################
data_scorpaena_porcus <- subset(week_kuds, Species == "Spor")

glmm_scorpaena_porcus <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_scorpaena_porcus, family = Gamma(link="log"))
summary(glmm_scorpaena_porcus)

boxplot(data_scorpaena_porcus$KUD95 ~ data_scorpaena_porcus$Spawn)
#################################################################################
data_scorpaena_scrofa <- subset(week_kuds, Species == "Sscr")

glmm_scorpaena_scrofa <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_scorpaena_scrofa, family = Gamma(link="log"))
summary(glmm_scorpaena_scrofa1)

boxplot(data_scorpaena_scrofa$KUD95 ~ data_scorpaena_scrofa$Spawn)
#################################################################################
data_seriola_dumerili <- subset(week_kuds, Species == "Sdum")

glmm_seriola_dumerili <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_seriola_dumerili, family = Gamma(link="log"))
summary(glmm_seriola_dumerili)

boxplot(data_seriola_dumerili$KUD95 ~ data_seriola_dumerili$Spawn)
#################################################################################
data_seriola_rivoliana <- subset(week_kuds, Species == "Sriv")

glmm_seriola_rivoliana <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_seriola_rivoliana, family = Gamma(link="log"))
summary(glmm_seriola_rivoliana)

boxplot(data_seriola_rivoliana$KUD95 ~ data_seriola_rivoliana$Spawn)
#################################################################################
data_serranus_atricauda <- subset(week_kuds, Species == "Satr")

glmm_serranus_atricauda <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_serranus_atricauda, family = Gamma(link="log"))
summary(glmm_serranus_atricauda)

boxplot(data_serranus_atricauda$KUD95 ~ data_serranus_atricauda$Spawn)
#################################################################################
data_serranus_scriba <- subset(week_kuds, Species == "Sscr")

glmm_serranus_scriba <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_serranus_scriba, family = Gamma(link="log"))
summary(glmm_serranus_scriba)

boxplot(data_serranus_scriba$KUD95 ~ data_serranus_scriba$Spawn)
#################################################################################
data_solea_senegalensis <- subset(week_kuds, Species == "Ssen")

glmm_solea_senegalensis <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_solea_senegalensis, family = Gamma(link="log"))
summary(glmm_solea_senegalensis)

boxplot(data_solea_senegalensis$KUD95 ~ data_solea_senegalensis$Spawn)
#################################################################################
data_sparisoma_cretense <- subset(week_kuds, Species == "Scre")

glmm_sparisoma_cretense <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_sparisoma_cretense, family = Gamma(link="log"))
summary(glmm_sparisoma_cretense)

boxplot(data_sparisoma_cretense$KUD95 ~ data_sparisoma_cretense$Spawn)
#################################################################################
data_sparus_aurata <- subset(week_kuds, Species == "Saur")

glmm_sparus_aurata <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_sparus_aurata, family = Gamma(link="log"))
summary(glmm_sparus_aurata)

boxplot(data_sparus_aurata$KUD95 ~ data_sparus_aurata$Spawn)
#################################################################################
data_sphyraena_viridensis <- subset(week_kuds, Species == "Svir")

glmm_sphyraena_viridensis <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_sphyraena_viridensis, family = Gamma(link="log"))
summary(glmm_sphyraena_viridensis)

boxplot(data_sphyraena_viridensis$KUD95 ~ data_sphyraena_viridensis$Spawn)
#################################################################################
data_spondyliosoma_cantharus <- subset(week_kuds, Species == "Scan")

glmm_spondyliosoma_cantharus <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=data_spondyliosoma_cantharus, family = Gamma(link="log"))
summary(glmm_spondyliosoma_cantharus)

boxplot(data_spondyliosoma_cantharus$KUD95 ~ data_spondyliosoma_cantharus$Spawn)
#################################################################################
```

```{r}
#Glmm KUD50 for each Species

data_dentex_dentex <- subset(week_kuds, Species == "Dden")

glmm_dentex_dentex <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_dentex_dentex, family = Gamma(link="log"))
summary(glmm_dentex_dentex)

boxplot(data_dentex_dentex$KUD50 ~ data_dentex_dentex$Spawn)
#################################################################################
data_dicentrarchus_labrax <- subset(week_kuds, Species == "Dlab")

glmm_dicentrarchus_labrax <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_dicentrarchus_labrax, family = Gamma(link="log"))
summary(glmm_dicentrarchus_labrax)

boxplot(data_dicentrarchus_labrax$KUD50 ~ data_dicentrarchus_labrax$Spawn)
#################################################################################
data_diplodus_cervinus <- subset(week_kuds, Species == "Dcer")

glmm_diplodus_cervinus <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_diplodus_cervinus, family = Gamma(link="log"))
summary(glmm_diplodus_cervinus)

boxplot(data_diplodus_cervinus$KUD50 ~ data_diplodus_cervinus$Spawn)
#################################################################################
data_diplodus_sargus <- subset(week_kuds, Species == "Dsar")

glmm_diplodus_sargus <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_diplodus_sargus, family = Gamma(link="log"))
summary(glmm_diplodus_sargus)

boxplot(data_diplodus_sargus$KUD50 ~ data_diplodus_sargus$Spawn)
#################################################################################
data_diplodus_vulgaris <- subset(week_kuds, Species == "Dvul")

glmm_diplodus_vulgaris <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_diplodus_vulgaris, family = Gamma(link="log"))
summary(glmm_diplodus_vulgaris)

boxplot(data_diplodus_vulgaris$KUD50 ~ data_diplodus_vulgaris$Spawn)
#################################################################################
data_epinephelus_marginatus <- subset(week_kuds, Species == "Emar")

glmm_epinephelus_marginatus <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_epinephelus_marginatus, family = Gamma(link="log"))
summary(glmm_epinephelus_marginatus)

boxplot(data_epinephelus_marginatus$KUD50 ~ data_epinephelus_marginatus$Spawn)
#################################################################################
data_gadus_morhua <- subset(week_kuds, Species == "Gmor")

glmm_gadus_morhua <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_gadus_morhua, family = Gamma(link="log"))
summary(glmm_gadus_morhua)

boxplot(data_gadus_morhua$KUD50 ~ data_gadus_morhua$Spawn)
#################################################################################
data_labrus_bergylta <- subset(week_kuds, Species == "Lber")

glmm_labrus_bergylta <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_labrus_bergylta, family = Gamma(link="log"))
summary(glmm_labrus_bergylta)

boxplot(data_labrus_bergylta$KUD50 ~ data_labrus_bergylta$Spawn)
#################################################################################
data_lichia_amia<- subset(week_kuds, Species == "Lami")

glmm_lichia_amia <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_lichia_amia, family = Gamma(link="log"))
summary(glmm_lichia_amia)

boxplot(data_lichia_amia$KUD50 ~ data_lichia_amia$Spawn)
#################################################################################
data_pagrus_pagrus <- subset(week_kuds, Species == "Ppag")

glmm_pagrus_pagrus <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_pagrus_pagrus, family = Gamma(link="log"))
summary(glmm_pagrus_pagrus)

boxplot(data_pagrus_pagrus$KUD50 ~ data_pagrus_pagrus$Spawn)
#################################################################################
data_pomatomus_saltatrix <- subset(week_kuds, Species == "Psal")

glmm_pomatomus_saltatrix <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_pomatomus_saltatrix, family = Gamma(link="log"))
summary(glmm_pomatomus_saltatrix)

boxplot(data_pomatomus_saltatrix$KUD50 ~ data_pomatomus_saltatrix$Spawn)
#################################################################################
data_pseudocaranx_dentex <- subset(week_kuds, Species == "Pden")

glmm_pseudocaranx_dentex <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_pseudocaranx_dentex, family = Gamma(link="log"))
summary(glmm_pseudocaranx_dentex)

boxplot(data_pseudocaranx_dentex$KUD50 ~ data_pseudocaranx_dentex$Spawn)
#################################################################################
data_sciaena_umbra <- subset(week_kuds, Species == "Sumb")

glmm_sciaena_umbra <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_sciaena_umbra, family = Gamma(link="log"))
summary(glmm_sciaena_umbra)

boxplot(data_sciaena_umbra$KUD50 ~ data_sciaena_umbra$Spawn)
#################################################################################
data_scorpaena_porcus <- subset(week_kuds, Species == "Spor")

glmm_scorpaena_porcus <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_scorpaena_porcus, family = Gamma(link="log"))
summary(glmm_scorpaena_porcus)

boxplot(data_scorpaena_porcus$KUD50 ~ data_scorpaena_porcus$Spawn)
#################################################################################
data_scorpaena_scrofa <- subset(week_kuds, Species == "Sscr")

glmm_scorpaena_scrofa <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_scorpaena_scrofa, family = Gamma(link="log"))
summary(glmm_scorpaena_scrofa1)

boxplot(data_scorpaena_scrofa$KUD95 ~ data_scorpaena_scrofa$Spawn)
#################################################################################
data_seriola_dumerili <- subset(week_kuds, Species == "Sdum")

glmm_seriola_dumerili <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_seriola_dumerili, family = Gamma(link="log"))
summary(glmm_seriola_dumerili)

boxplot(data_seriola_dumerili$KUD50 ~ data_seriola_dumerili$Spawn)
#################################################################################
data_seriola_rivoliana <- subset(week_kuds, Species == "Sriv")

glmm_seriola_rivoliana <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_seriola_rivoliana, family = Gamma(link="log"))
summary(glmm_seriola_rivoliana)

boxplot(data_seriola_rivoliana$KUD50 ~ data_seriola_rivoliana$Spawn)
#################################################################################
data_serranus_atricauda <- subset(week_kuds, Species == "Satr")

glmm_serranus_atricauda <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_serranus_atricauda, family = Gamma(link="log"))
summary(glmm_serranus_atricauda)

boxplot(data_serranus_atricauda$KUD50 ~ data_serranus_atricauda$Spawn)
#################################################################################
data_serranus_scriba <- subset(week_kuds, Species == "Sscr")

glmm_serranus_scriba <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_serranus_scriba, family = Gamma(link="log"))
summary(glmm_serranus_scriba)

boxplot(data_serranus_scriba$KUD50 ~ data_serranus_scriba$Spawn)
#################################################################################
data_solea_senegalensis <- subset(week_kuds, Species == "Ssen")

glmm_solea_senegalensis <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_solea_senegalensis, family = Gamma(link="log"))
summary(glmm_solea_senegalensis)

boxplot(data_solea_senegalensis$KUD50 ~ data_solea_senegalensis$Spawn)
#################################################################################
data_sparisoma_cretense <- subset(week_kuds, Species == "Scre")

glmm_sparisoma_cretense <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_sparisoma_cretense, family = Gamma(link="log"))
summary(glmm_sparisoma_cretense)

boxplot(data_sparisoma_cretense$KUD50 ~ data_sparisoma_cretense$Spawn)
#################################################################################
data_sparus_aurata <- subset(week_kuds, Species == "Saur")

glmm_sparus_aurata <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_sparus_aurata, family = Gamma(link="log"))
summary(glmm_sparus_aurata)

boxplot(data_sparus_aurata$KUD50 ~ data_sparus_aurata$Spawn)
#################################################################################
data_sphyraena_viridensis <- subset(week_kuds, Species == "Svir")

glmm_sphyraena_viridensis <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_sphyraena_viridensis, family = Gamma(link="log"))
summary(glmm_sphyraena_viridensis)

boxplot(data_sphyraena_viridensis$KUD50 ~ data_sphyraena_viridensis$Spawn)
#################################################################################
data_spondyliosoma_cantharus <- subset(week_kuds, Species == "Scan")

glmm_spondyliosoma_cantharus <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_spondyliosoma_cantharus, family = Gamma(link="log"))
summary(glmm_spondyliosoma_cantharus)

boxplot(data_spondyliosoma_cantharus$KUD50 ~ data_spondyliosoma_cantharus$Spawn)
#################################################################################
```

```{r}
#Glmm KUD50 for each File

data_dentex_dentex1 <- subset(week_kuds, File == "Dentex_dentex1")

glmm_dentex_dentex1 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_dentex_dentex1, family = Gamma(link="log"))
summary(glmm_dentex_dentex1)

boxplot(data_dentex_dentex1$KUD50 ~ data_dentex_dentex1$Spawn)
#################################################################################
data_dentex_dentex2 <- subset(week_kuds, File == "Dentex_dentex2")

glmm_dentex_dentex2 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_dentex_dentex2, family = Gamma(link="log"))
summary(glmm_dentex_dentex2)

boxplot(data_dentex_dentex2$KUD50 ~ data_dentex_dentex2$Spawn)
#################################################################################
data_dicentrarchus_labrax1 <- subset(week_kuds, File == "Dicentrarchus_labrax1")

glmm_dicentrarchus_labrax1 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_dicentrarchus_labrax1, family = Gamma(link="log"))
summary(glmm_dicentrarchus_labrax1)

boxplot(data_dicentrarchus_labrax1$KUD50 ~ data_dicentrarchus_labrax1$Spawn)
#################################################################################
data_dicentrarchus_labrax2 <- subset(week_kuds, File == "Dicentrarchus_labrax2")

glmm_dicentrarchus_labrax2 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_dicentrarchus_labrax2, family = Gamma(link="log"))
summary(glmm_dicentrarchus_labrax2)

boxplot(data_dicentrarchus_labrax2$KUD50 ~ data_dicentrarchus_labrax2$Spawn)
#################################################################################
data_diplodus_cervinus <- subset(week_kuds, File == "Diplodus_cervinus")

glmm_diplodus_cervinus <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_diplodus_cervinus, family = Gamma(link="log"))
summary(glmm_diplodus_cervinus)

boxplot(data_diplodus_cervinus$KUD50 ~ data_diplodus_cervinus$Spawn)
#################################################################################
data_diplodus_sargus1 <- subset(week_kuds, File == "Diplodus_sargus1")

glmm_diplodus_sargus1 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_diplodus_sargus1, family = Gamma(link="log"))
summary(glmm_diplodus_sargus1)

boxplot(data_diplodus_sargus1$KUD50 ~ data_diplodus_sargus1$Spawn)
#################################################################################
data_diplodus_sargus2 <- subset(week_kuds, File == "Diplodus_sargus2")

glmm_diplodus_sargus2 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_diplodus_sargus2, family = Gamma(link="log"))
summary(glmm_diplodus_sargus2)

boxplot(data_diplodus_sargus2$KUD50 ~ data_diplodus_sargus2$Spawn)
#################################################################################
data_diplodus_sargus3 <- subset(week_kuds, File == "Diplodus_sargus3")

glmm_diplodus_sargus3 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_diplodus_sargus3, family = Gamma(link="log"))
summary(glmm_diplodus_sargus3)

boxplot(data_diplodus_sargus3$KUD50 ~ data_diplodus_sargus3$Spawn)
#################################################################################
data_diplodus_sargus4 <- subset(week_kuds, File == "Diplodus_sargus4")

glmm_diplodus_sargus4 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_diplodus_sargus4, family = Gamma(link="log"))
summary(glmm_diplodus_sargus4)

boxplot(data_diplodus_sargus4$KUD50 ~ data_diplodus_sargus4$Spawn)
#################################################################################
data_diplodus_sargus5 <- subset(week_kuds, File == "Diplodus_sargus5")

glmm_diplodus_sargus5 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_diplodus_sargus5, family = Gamma(link="log"))
summary(glmm_diplodus_sargus5)

boxplot(data_diplodus_sargus5$KUD50 ~ data_diplodus_sargus5$Spawn)
#################################################################################
data_diplodus_sargus6 <- subset(week_kuds, File == "Diplodus_sargus6")

glmm_diplodus_sargus6 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_diplodus_sargus6, family = Gamma(link="log"))
summary(glmm_diplodus_sargus6)

boxplot(data_diplodus_sargus6$KUD50 ~ data_diplodus_sargus6$Spawn)
#################################################################################
data_diplodus_vulgaris1 <- subset(week_kuds, File == "Diplodus_vulgaris1")

glmm_diplodus_vulgaris1 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_diplodus_vulgaris1, family = Gamma(link="log"))
summary(glmm_diplodus_vulgaris1)

boxplot(data_diplodus_vulgaris1$KUD50 ~ data_diplodus_vulgaris1$Spawn)
#################################################################################
data_diplodus_vulgaris2 <- subset(week_kuds, File == "Diplodus_vulgaris2")

glmm_diplodus_vulgaris2 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_diplodus_vulgaris2, family = Gamma(link="log"))
summary(glmm_diplodus_vulgaris2)

boxplot(data_diplodus_vulgaris2$KUD50 ~ data_diplodus_vulgaris2$Spawn)
#################################################################################
data_epinephelus_marginatus1 <- subset(week_kuds, File == "Epinephelus_marginatus1")

glmm_epinephelus_marginatus1 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_epinephelus_marginatus1, family = Gamma(link="log"))
summary(glmm_epinephelus_marginatus1)

boxplot(data_epinephelus_marginatus1$KUD50 ~ data_epinephelus_marginatus1$Spawn)
#################################################################################
data_epinephelus_marginatus2 <- subset(week_kuds, File == "Epinephelus_marginatus2")

glmm_epinephelus_marginatus2 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_epinephelus_marginatus2, family = Gamma(link="log"))
summary(glmm_epinephelus_marginatus2)

boxplot(data_epinephelus_marginatus2$KUD50 ~ data_epinephelus_marginatus2$Spawn)
#################################################################################
data_epinephelus_marginatus3 <- subset(week_kuds, File == "Epinephelus_marginatus3")

glmm_epinephelus_marginatus3 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_epinephelus_marginatus3, family = Gamma(link="log"))
summary(glmm_epinephelus_marginatus3)

boxplot(data_epinephelus_marginatus3$KUD50 ~ data_epinephelus_marginatus3$Spawn)
#################################################################################
data_epinephelus_marginatus4 <- subset(week_kuds, File == "Epinephelus_marginatus4")

glmm_epinephelus_marginatus4 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_epinephelus_marginatus4, family = Gamma(link="log"))
summary(glmm_epinephelus_marginatus4)

boxplot(data_epinephelus_marginatus4$KUD50 ~ data_epinephelus_marginatus4$Spawn)
#################################################################################
data_gadus_morhua1 <- subset(week_kuds, File == "Gadus_morhua1")

glmm_gadus_morhua1 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_gadus_morhua1, family = Gamma(link="log"))
summary(glmm_gadus_morhua1)

boxplot(data_gadus_morhua1$KUD50 ~ data_gadus_morhua1$Spawn)
#################################################################################
data_gadus_morhua2 <- subset(week_kuds, File == "Gadus_morhua2")

glmm_gadus_morhua2 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_gadus_morhua2, family = Gamma(link="log"))
summary(glmm_gadus_morhua2)

boxplot(data_gadus_morhua2$KUD50 ~ data_gadus_morhua2$Spawn)
#################################################################################
data_gadus_morhua3 <- subset(week_kuds, File == "Gadus_morhua3")

glmm_gadus_morhua3 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_gadus_morhua3, family = Gamma(link="log"))
summary(glmm_gadus_morhua3)

boxplot(data_gadus_morhua3$KUD50 ~ data_gadus_morhua3$Spawn)
#################################################################################
data_labrus_bergylta <- subset(week_kuds, File == "Labrus_bergylta")

glmm_labrus_bergylta <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_labrus_bergylta, family = Gamma(link="log"))
summary(glmm_labrus_bergylta)

boxplot(data_labrus_bergylta$KUD50 ~ data_labrus_bergylta$Spawn)
#################################################################################
data_lichia_amia<- subset(week_kuds, File == "Lichia_amia")

glmm_lichia_amia <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_lichia_amia, family = Gamma(link="log"))
summary(glmm_lichia_amia)

boxplot(data_lichia_amia$KUD50 ~ data_lichia_amia$Spawn)
#################################################################################
data_pagrus_pagrus1 <- subset(week_kuds, File == "Pagrus_pagrus1")

glmm_pagrus_pagrus1 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_pagrus_pagrus1, family = Gamma(link="log"))
summary(glmm_pagrus_pagrus1)

boxplot(data_pagrus_pagrus1$KUD50 ~ data_pagrus_pagrus1$Spawn)
#################################################################################
data_pagrus_pagrus2 <- subset(week_kuds, File == "Pagrus_pagrus2")

glmm_pagrus_pagrus2 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_pagrus_pagrus2, family = Gamma(link="log"))
summary(glmm_pagrus_pagrus2)

boxplot(data_pagrus_pagrus2$KUD50 ~ data_pagrus_pagrus2$Spawn)
#################################################################################
data_pomatomus_saltatrix <- subset(week_kuds, File == "Pomatomus_saltatrix")

glmm_pomatomus_saltatrix <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_pomatomus_saltatrix, family = Gamma(link="log"))
summary(glmm_pomatomus_saltatrix)

boxplot(data_pomatomus_saltatrix$KUD50 ~ data_pomatomus_saltatrix$Spawn)
#################################################################################
data_pseudocaranx_dentex <- subset(week_kuds, File == "Pseudocaranx_dentex")

glmm_pseudocaranx_dentex <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_pseudocaranx_dentex, family = Gamma(link="log"))
summary(glmm_pseudocaranx_dentex)

boxplot(data_pseudocaranx_dentex$KUD50 ~ data_pseudocaranx_dentex$Spawn)
#################################################################################
data_sciaena_umbra1 <- subset(week_kuds, File == "Sciaena_umbra1")

glmm_sciaena_umbra1 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_sciaena_umbra1, family = Gamma(link="log"))
summary(glmm_sciaena_umbra1)

boxplot(data_sciaena_umbra1$KUD50 ~ data_sciaena_umbra1$Spawn)
#################################################################################
data_sciaena_umbra2 <- subset(week_kuds, File == "Sciaena_umbra2")

glmm_sciaena_umbra2 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_sciaena_umbra2, family = Gamma(link="log"))
summary(glmm_sciaena_umbra2)

boxplot(data_sciaena_umbra2$KUD50 ~ data_sciaena_umbra2$Spawn)
#################################################################################
data_scorpaena_porcus <- subset(week_kuds, File == "Scorpaena_porcus")

glmm_scorpaena_porcus <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_scorpaena_porcus, family = Gamma(link="log"))
summary(glmm_scorpaena_porcus)

boxplot(data_scorpaena_porcus$KUD50 ~ data_scorpaena_porcus$Spawn)
#################################################################################
data_scorpaena_scrofa1 <- subset(week_kuds, File == "Scorpaena_scrofa1")

glmm_scorpaena_scrofa1 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_scorpaena_scrofa1, family = Gamma(link="log"))
summary(glmm_scorpaena_scrofa1)

boxplot(data_scorpaena_scrofa1$KUD50 ~ data_scorpaena_scrofa1$Spawn)
#################################################################################
data_scorpaena_scrofa2 <- subset(week_kuds, File == "Scorpaena_scrofa2")

glmm_scorpaena_scrofa2 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_scorpaena_scrofa2, family = Gamma(link="log"))
summary(glmm_scorpaena_scrofa2)

boxplot(data_scorpaena_scrofa2$KUD50 ~ data_scorpaena_scrofa2$Spawn)
#################################################################################
data_seriola_dumerili <- subset(week_kuds, File == "Seriola_dumerili")

glmm_seriola_dumerili <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_seriola_dumerili, family = Gamma(link="log"))
summary(glmm_seriola_dumerili)

boxplot(data_seriola_dumerili$KUD50 ~ data_seriola_dumerili$Spawn)
#################################################################################
data_seriola_rivoliana <- subset(week_kuds, File == "Seriola_rivoliana")

glmm_seriola_rivoliana <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_seriola_rivoliana, family = Gamma(link="log"))
summary(glmm_seriola_rivoliana)

boxplot(data_seriola_rivoliana$KUD50 ~ data_seriola_rivoliana$Spawn)
#################################################################################
data_serranus_atricauda <- subset(week_kuds, File == "Serranus_atricauda")

glmm_serranus_atricauda <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_serranus_atricauda, family = Gamma(link="log"))
summary(glmm_serranus_atricauda)

boxplot(data_serranus_atricauda$KUD50 ~ data_serranus_atricauda$Spawn)
#################################################################################
data_serranus_scriba <- subset(week_kuds, File == "Serranus_scriba")

glmm_serranus_scriba <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_serranus_scriba, family = Gamma(link="log"))
summary(glmm_serranus_scriba)

boxplot(data_serranus_scriba$KUD50 ~ data_serranus_scriba$Spawn)
#################################################################################
data_solea_senegalensis <- subset(week_kuds, File == "Solea_senegalensis")

glmm_solea_senegalensis <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_solea_senegalensis, family = Gamma(link="log"))
summary(glmm_solea_senegalensis)

boxplot(data_solea_senegalensis$KUD50 ~ data_solea_senegalensis$Spawn)
#################################################################################
data_sparisoma_cretense <- subset(week_kuds, File == "Sparisoma_cretense")

glmm_sparisoma_cretense <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_sparisoma_cretense, family = Gamma(link="log"))
summary(glmm_sparisoma_cretense)

boxplot(data_sparisoma_cretense$KUD50 ~ data_sparisoma_cretense$Spawn)
#################################################################################
data_sparus_aurata1 <- subset(week_kuds, File == "Sparus_aurata1")

glmm_sparus_aurata1 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_sparus_aurata1, family = Gamma(link="log"))
summary(glmm_sparus_aurata1)

boxplot(data_sparus_aurata1$KUD50 ~ data_sparus_aurata1$Spawn)
#################################################################################
data_sparus_aurata2 <- subset(week_kuds, File == "Sparus_aurata2")

glmm_sparus_aurata2 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_sparus_aurata2, family = Gamma(link="log"))
summary(glmm_sparus_aurata2)

boxplot(data_sparus_aurata2$KUD50 ~ data_sparus_aurata2$Spawn)
#################################################################################
data_sphyraena_viridensis1 <- subset(week_kuds, File == "Sphyraena_viridensis1")

glmm_sphyraena_viridensis1 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_sphyraena_viridensis1, family = Gamma(link="log"))
summary(glmm_sphyraena_viridensis1)

boxplot(data_sphyraena_viridensis1$KUD50 ~ data_sphyraena_viridensis1$Spawn)
#################################################################################
data_sphyraena_viridensis2 <- subset(week_kuds, File == "Sphyraena_viridensis2")

glmm_sphyraena_viridensis2 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_sphyraena_viridensis2, family = Gamma(link="log"))
summary(glmm_sphyraena_viridensis2)

boxplot(data_sphyraena_viridensis2$KUD50 ~ data_sphyraena_viridensis2$Spawn)
#################################################################################
data_spondyliosoma_cantharus <- subset(week_kuds, File == "Spondyliosoma_cantharus")

glmm_spondyliosoma_cantharus <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=data_spondyliosoma_cantharus, family = Gamma(link="log"))
summary(glmm_spondyliosoma_cantharus)

boxplot(data_spondyliosoma_cantharus$KUD50 ~ data_spondyliosoma_cantharus$Spawn)
#################################################################################
```

```{r}
#Spawn
lm_spawn <- lm(KUD95 ~ Spawn, data=week_kuds)
glm_spawn <- glm(KUD95 ~ Spawn, data=week_kuds, family=Gamma(link="log"))
gam_spawn <- gam(KUD95 ~ Spawn, data=week_kuds, family=Gamma(link="log"))
glmmF_spawn <- glmmTMB(KUD95 ~ Spawn + (1|File), data=week_kuds, family=Gamma(link="log"))
glmmT_spawn <- glmmTMB(KUD95 ~ Spawn + (1|Transmitter), data=week_kuds, family=Gamma(link="log"))
glmmS_spawn <- glmmTMB(KUD95 ~ Spawn + (1|Species), data=week_kuds, family=Gamma(link="log"))
gammF_spawn <- gamm(KUD95 ~ Spawn, random=list(File=~1), data= week_kuds, family=Gamma(link="log"))   #Preference for gmcv package since gamm4 uses glm methods
#gamm4F_spawn <- gamm4(KUD95 ~ Spawn, random = ~(1|File), data = week_kuds, family=Gamma(link="log"))
gammT_spawn <- gamm(KUD95 ~ Spawn, random=list(Transmitter=~1), data= week_kuds, family=Gamma(link="log"))   #Preference for gmcv package since gamm4 uses glm methods
#gamm4T_spawn <- gamm4(KUD95 ~ Spawn, random = ~(1|Transmitter), data = week_kuds, family=Gamma(link="log"))
gammS_spawn <- gamm(KUD95 ~ Spawn, random=list(Species=~1), data= week_kuds, family=Gamma(link="log"))   #Preference for gmcv package since gamm4 uses glm methods
#gamm4S_spawn <- gamm4(KUD95 ~ Spawn, random = ~(1|Species), data = week_kuds, family=Gamma(link="log"))

AIC(lm_spawn, glm_spawn, gam_spawn, glmmF_spawn, glmmT_spawn, glmmS_spawn)
summary(gammF_spawn$lme)
summary(gammT_spawn$lme)
summary(gammS_spawn$lme)

#Spawn
lm_spawn1 <- lm(KUD50 ~ Spawn, data=week_kuds)
glm_spawn1 <- glm(KUD50 ~ Spawn, data=week_kuds, family=Gamma(link="log"))
gam_spawn1 <- gam(KUD50 ~ Spawn, data=week_kuds, family=Gamma(link="log"))
glmmF_spawn1 <- glmmTMB(KUD50 ~ Spawn + (1|File), data=week_kuds, family=Gamma(link="log"))
glmmT_spawn1 <- glmmTMB(KUD50 ~ Spawn + (1|Transmitter), data=week_kuds, family=Gamma(link="log"))
glmmS_spawn1 <- glmmTMB(KUD50 ~ Spawn + (1|Species), data=week_kuds, family=Gamma(link="log"))
gammF_spawn1 <- gamm(KUD50 ~ Spawn, random=list(File=~1), data= week_kuds, family=Gamma(link="log"))   #Preference for gmcv package since gamm4 uses glm methods
#gamm4F_spawn1 <- gamm4(KUD50 ~ Spawn, random = ~(1|File), data = week_kuds, family=Gamma(link="log"))
gammT_spawn1 <- gamm(KUD50 ~ Spawn, random=list(Transmitter=~1), data= week_kuds, family=Gamma(link="log"))   #Preference for gmcv package since gamm4 uses glm methods
#gamm4T_spawn1 <- gamm4(KUD50 ~ Spawn, random = ~(1|Transmitter), data = week_kuds, family=Gamma(link="log"))
gammS_spawn1 <- gamm(KUD50 ~ Spawn, random=list(Species=~1), data= week_kuds, family=Gamma(link="log"))   #Preference for gmcv package since gamm4 uses glm methods
#gamm4S_spawn1 <- gamm4(KUD50 ~ Spawn, random = ~(1|Species), data = week_kuds, family=Gamma(link="log"))

AIC(lm_spawn1, glm_spawn1, gam_spawn1, glmmF_spawn1, glmmT_spawn1, glmmS_spawn1)
summary(gammF_spawn1$lme)
summary(gammT_spawn1$lme)
summary(gammS_spawn1$lme)
```

```{r}
glmmT_total <- glmmTMB(KUD95 ~ LengthStd + BodyMassStd + Longevity + Vulnerability + Troph + Habitat + Migration + ComImport + Spawn + ReceiverDensity + MonitArea_km2 + (1|Transmitter), data=week_kuds, family=Gamma(link="log"))

glmmF_total <- glmmTMB(KUD95 ~ LengthStd + BodyMassStd + Longevity + Vulnerability + Troph + Habitat + Migration + ComImport + Spawn + ReceiverDensity + MonitArea_km2 + (1|File), data=week_kuds, family=Gamma(link="log"))

glmmS_total <- glmmTMB(KUD95 ~ LengthStd + BodyMassStd + Longevity + Vulnerability + Troph + Habitat + Migration + ComImport + Spawn + ReceiverDensity + MonitArea_km2 + (1|Species), data=week_kuds, family=Gamma(link="log"))

glmmTF_total <- glmmTMB(KUD95 ~ LengthStd + BodyMassStd + Longevity + Vulnerability + Troph + Habitat + Migration + ComImport + Spawn + ReceiverDensity + MonitArea_km2 + (1|Transmitter) + (1|File), data=week_kuds, family=Gamma(link="log"))

glmmTS_total <- glmmTMB(KUD95 ~ LengthStd + BodyMassStd + Longevity + Vulnerability + Troph + Habitat + Migration + ComImport + Spawn + ReceiverDensity + MonitArea_km2 + (1|Transmitter) + (1|Species), data=week_kuds, family=Gamma(link="log"))

glmmFS_total <- glmmTMB(KUD95 ~ LengthStd + BodyMassStd + Longevity + Vulnerability + Troph + Habitat + Migration + ComImport + Spawn + ReceiverDensity + MonitArea_km2 + (1|File) + (1|Species), data=week_kuds, family=Gamma(link="log"))

glmmTFS_total <- glmmTMB(KUD95 ~ LengthStd + BodyMassStd + Longevity + Vulnerability + Troph + Habitat + Migration + ComImport + Spawn + ReceiverDensity + MonitArea_km2 + (1|Transmitter) + (1|File) + (1|Species), data=week_kuds, family=Gamma(link="log"))


AIC(glmmT_total, glmmF_total, glmmS_total, glmmTF_total, glmmTS_total, glmmFS_total, glmmTFS_total)

#Now we need to compare if the models are statistically different or not
anova(glmmT_total, glmmTF_total) #significant differences, this two models differ statistically
anova(glmmT_total, glmmTFS_total) #significant differences, this two models differ statistically
anova(glmmTF_total, glmmTFS_total) #non significant differences, this two models do not differ statistically
anova(glmmTF_total, glmmTS_total) #non significant differences, this two models do not differ statistically
anova(glmmTS_total, glmmTFS_total) #significant differences, this two models differ statistically

#choose the simplest model with the lower AIC, that is statistically different from the others, which means the model with Transmitter and File as random effect (glmmTF_total)
```

```{r}
#Backward elimination KUD95

Total1 <- glmmTMB(KUD95 ~ LengthStd + BodyMassStd + Longevity + Vulnerability + Troph + Habitat + Migration + ComImport + Spawn + ReceiverDensity + MonitArea_km2 + (1|Transmitter) + (1|Species), data = week_kuds, family = Gamma(link="log"))
summary(Total1)

Total2 <- glmmTMB(KUD95 ~ LengthStd + BodyMassStd + Vulnerability + Troph + Habitat + Migration + ComImport + Spawn + ReceiverDensity + MonitArea_km2 + (1|Transmitter) + (1|Species), data = week_kuds, family = Gamma(link="log"))
summary(Total2)

Total3 <- glmmTMB(KUD95 ~ LengthStd + BodyMassStd + Vulnerability + Habitat + Migration + ComImport + Spawn + ReceiverDensity + MonitArea_km2 + (1|Transmitter) + (1|Species), data = week_kuds, family = Gamma(link="log"))
summary(Total3)

Total4 <- glmmTMB(KUD95 ~ LengthStd + Vulnerability + Habitat + Migration + ComImport + Spawn + ReceiverDensity + MonitArea_km2 + (1|Transmitter) + (1|Species), data = week_kuds, family = Gamma(link="log"))
summary(Total4)

Total5 <- glmmTMB(KUD95 ~ LengthStd + Vulnerability + Habitat + ComImport + Spawn + ReceiverDensity + MonitArea_km2 + (1|Transmitter) + (1|Species), data = week_kuds, family = Gamma(link="log"))
summary(Total5)

Total6 <- glmmTMB(KUD95 ~ LengthStd + Vulnerability + Habitat + ComImport + Spawn + MonitArea_km2 + (1|Transmitter) + (1|Species), data = week_kuds, family = Gamma(link="log"))
summary(Total6)

Total7 <- glmmTMB(KUD95 ~ LengthStd + Habitat + ComImport + Spawn + MonitArea_km2 + (1|Transmitter) + (1|Species), data = week_kuds, family = Gamma(link="log"))
summary(Total7)
```

```{r}
#Test residuals for the best model (goodness of fit)
testDispersion(Total7)  #plot with normality, dispersion and outliers

simulationOutput <- simulateResiduals(fittedModel = Total7, plot = F) #dispersion test
testDispersion(simulationOutput) #dispersion test

plot(simulationOutput) #residual analysis
plotQQunif(simulationOutput) #Q-Q plot (normality checking)
plotResiduals(simulationOutput) #residual vs. predicted (homoscedasticity checking)
testOutliers(simulationOutput) #outliers checking

#Simulations from the model
getObservedResponse(Total7)  #response used to fit the model
getFitted(Total7)  #predictions of the model for all points
x = getSimulations(Total7, nsim = 5, type = "refit")  #extract simulations from the model
getRefit(Total7, x[[1]])  #model with simulated data
getRefit(Total7, getObservedResponse(Total7))  #model with real data

#create a dataframe with the simulated data and the true data
df <- data.frame(x$sim_1, x$sim_2, x$sim_3, week_kuds$KUD95, week_kuds$LengthStd, week_kuds$Habitat, week_kuds$ComImport, week_kuds$Spawn)

#plot KUD95 (real and simulated) against Length Std
grid.arrange(ggplot(data= df, aes(x = week_kuds.LengthStd, y=week_kuds.KUD95)) + geom_point(col="black") +  scale_y_continuous(limits = c(0, 15)) + xlab("Length Std") + ylab("real KUD95"), ggplot(data= df, aes(x = week_kuds.LengthStd, y=x.sim_1)) + geom_point(col="lightblue4") +  scale_y_continuous(limits = c(0, 15)) + xlab("Length Std") + ylab("KUD95 simulation 1"), ggplot(data= df, aes(x = week_kuds.LengthStd, y=x.sim_2)) + geom_point(col="deepskyblue3") +  scale_y_continuous(limits = c(0, 15)) + xlab("Length Std") + ylab("KUD95 simulation 2"), ggplot(data= df, aes(x = week_kuds.LengthStd, y=x.sim_3)) + geom_point(col="deepskyblue4") +  scale_y_continuous(limits = c(0, 15)) + xlab("Length Std") + ylab("KUD95 simulation 3"))

#plot KUD95 (real and simulated) against Commercial Importance
grid.arrange(ggplot(data = df, aes(x = week_kuds.ComImport, y=week_kuds.KUD95)) +
  geom_boxplot(fill = "black") + scale_y_continuous(limits = c(0, 15)) + xlab("Commercial Importance") + ylab("real KUD95"), ggplot(data = df, aes(x = week_kuds.ComImport, y=x.sim_1)) +
  geom_boxplot(fill = "lightblue4") + scale_y_continuous(limits = c(0, 15)) + xlab("Commercial Importance") + ylab("KUD95 simulation 1"), ggplot(data = df, aes(x = week_kuds.ComImport, y=x.sim_2)) +
  geom_boxplot(fill = "deepskyblue3") + scale_y_continuous(limits = c(0, 15)) + xlab("Commercial Importance") + ylab("KUD95 simulation 2"), ggplot(data = df, aes(x = week_kuds.ComImport, y=x.sim_3)) + geom_boxplot(fill = "deepskyblue4") + scale_y_continuous(limits = c(0, 15)) + xlab("Commercial Importance") + ylab("KUD95 simulation 3"), ncol = 4)

#plot KUD95 (real and simulated) against Habitat
grid.arrange(ggplot(data = df, aes(x = week_kuds.Habitat, y=week_kuds.KUD95)) +
  geom_boxplot(fill = "black") + scale_y_continuous(limits = c(0, 15)) + xlab("Habitat") + ylab("real KUD95"), ggplot(data = df, aes(x = week_kuds.Habitat, y=x.sim_1)) +
  geom_boxplot(fill = "lightblue4") + scale_y_continuous(limits = c(0, 15)) + xlab("Habitat") + ylab("KUD95 simulation 1"), ggplot(data = df, aes(x = week_kuds.Habitat, y=x.sim_2)) +
  geom_boxplot(fill = "deepskyblue3") + scale_y_continuous(limits = c(0, 15)) + xlab("Habitat") + ylab("KUD95 simulation 2"), ggplot(data = df, aes(x = week_kuds.Habitat, y=x.sim_3)) + geom_boxplot(fill = "deepskyblue4") + scale_y_continuous(limits = c(0, 15)) + xlab("Habitat") + ylab("KUD95 simulation 3"), ncol = 4)

#plot KUD95 (real and simulated) against Spawn
grid.arrange(ggplot(data = df, aes(x = week_kuds.Spawn, y=week_kuds.KUD95)) +
  geom_boxplot(fill = "black") + scale_y_continuous(limits = c(0, 15)) + xlab("Spawn") + ylab("real KUD95"), ggplot(data = df, aes(x = week_kuds.Spawn, y=x.sim_1)) +
  geom_boxplot(fill = "lightblue4") + scale_y_continuous(limits = c(0, 15)) + xlab("Spawn") + ylab("KUD95 simulation 1"), ggplot(data = df, aes(x = week_kuds.Spawn, y=x.sim_2)) +
  geom_boxplot(fill = "deepskyblue3") + scale_y_continuous(limits = c(0, 15)) + xlab("Spawn") + ylab("KUD95 simulation 2"), ggplot(data = df, aes(x = week_kuds.Spawn, y=x.sim_3)) + geom_boxplot(fill = "deepskyblue4") + scale_y_continuous(limits = c(0, 15)) + xlab("Spawn") + ylab("KUD95 simulation 3"), ncol = 4)
```


```{r}
#Backward elimination KUD50

Total1.1 <- glmmTMB(KUD50 ~ LengthStd + BodyMassStd + Longevity + Vulnerability + Troph + Habitat + Migration + ComImport + Spawn + ReceiverDensity + MonitArea_km2 + (1|Transmitter) + (1|Species), data = week_kuds, family = Gamma(link="log"))
summary(Total1.1)

Total1.2 <- glmmTMB(KUD50 ~ LengthStd + Longevity + Vulnerability + Troph + Habitat + Migration + ComImport + Spawn + ReceiverDensity + MonitArea_km2 + (1|Transmitter) + (1|Species), data = week_kuds, family = Gamma(link="log"))
summary(Total1.2)

Total1.3 <- glmmTMB(KUD50 ~ LengthStd + Longevity + Vulnerability + Troph + Habitat + Migration + ComImport + Spawn + MonitArea_km2 + (1|Transmitter) + (1|Species), data = week_kuds, family = Gamma(link="log"))
summary(Total1.3)

Total1.4 <- glmmTMB(KUD50 ~ LengthStd + Vulnerability + Troph + Habitat + Migration + ComImport + Spawn + MonitArea_km2 + (1|Transmitter) + (1|Species), data = week_kuds, family = Gamma(link="log"))
summary(Total1.4)

Total1.5 <- glmmTMB(KUD50 ~ LengthStd + Vulnerability + Troph + Habitat + ComImport + Spawn + MonitArea_km2 + (1|Transmitter) + (1|Species), data = week_kuds, family = Gamma(link="log"))
summary(Total1.5)

Total1.6 <- glmmTMB(KUD50 ~ LengthStd + Vulnerability + Habitat + ComImport + Spawn + MonitArea_km2 + (1|Transmitter) + (1|Species), data = week_kuds, family = Gamma(link="log"))
summary(Total1.6)

Total1.7 <- glmmTMB(KUD50 ~ LengthStd + Habitat + ComImport + Spawn + MonitArea_km2 + (1|Transmitter) + (1|Species), data = week_kuds, family = Gamma(link="log"))
summary(Total1.7)

Total1.8 <- glmmTMB(KUD50 ~ LengthStd + Habitat + Spawn + MonitArea_km2 + (1|Transmitter) + (1|Species), data = week_kuds, family = Gamma(link="log"))
summary(Total1.8)
```




```{r}
#Exploratory analysis
plot(week_kuds$Week, week_kuds$KUD95)
glm_week <- glm(KUD95 ~ Week, data = week_kuds, family=Gamma(link="log"))
with(week_kuds, plot(KUD95 ~ Week, pch = 1, col="deepskyblue"))
seq <- levels(week_kuds$Week)
predictweek <- predict(glm_week,newdata=data.frame(Week=seq), type="response")
lines(seq, predictweek, lty=1, col="red")

week_kuds$Week <- as.numeric(week_kuds$Week)

##See how KUD varies over Weeks by Spawning season
week_kuds_ss <- subset(week_kuds, SpawnSeason == "SS")
week_kuds_a <- subset(week_kuds, SpawnSeason == "A")
week_kuds_w <- subset(week_kuds, SpawnSeason == "W")

grid.arrange(
ggplot(week_kuds_ss, aes(x = Week, y = KUD95)) +
  geom_point(col = "green") +
  labs(title = "KUD95 over Weeks SS",
       x = "Week",
       y = "KUD95") +
  scale_y_continuous(limits = c(0, 15)) +
  theme_minimal() ,


ggplot(week_kuds_a, aes(x = Week, y = KUD95)) +
  geom_point(col = "red") +
  labs(title = "KUD95 over Weeks A",
       x = "Week",
       y = "KUD95") +
  scale_y_continuous(limits = c(0, 15)) +
  theme_minimal() ,

ggplot(week_kuds_w, aes(x = Week, y = KUD95)) +
  geom_point(col = "blue") +
  labs(title = "KUD95 over Weeks W",
       x = "Week",
       y = "KUD95") +
  scale_y_continuous(limits = c(0, 15)) +
  theme_minimal()
)

#With predictions
#SS
gam_ss <- gam(KUD95 ~ s(Week), data = week_kuds_ss[week_kuds_ss$SpawnSeason == "SS", ], family = Gamma(link = "log"))
summary(gam_ss)

week_kuds_ss$predicted <- predict(gam_ss, newdata = week_kuds_ss, type = "response")

plotss<- ggplot(week_kuds_ss, aes(x = Week, y = KUD95)) +
  geom_point(col = "green") +
  geom_line(aes(y = predicted), col = "black", linetype = "dashed") +
  labs(title = "KUD95 over Weeks (SpawnSeason = SS)",
       x = "Week",
       y = "KUD95") +
  scale_y_continuous(limits = c(0, 15)) +
  theme_minimal()

#SA
gam_a <- gam(KUD95 ~ s(Week), data = week_kuds_a[week_kuds_a$SpawnSeason == "A", ], family = Gamma(link = "log"))
summary(gam_a)

week_kuds_a$predicted <- predict(gam_a, newdata = week_kuds_a, type = "response")

plota <- ggplot(week_kuds_a, aes(x = Week, y = KUD95)) +
  geom_point(col = "red") +
  geom_line(aes(y = predicted), col = "black", linetype = "dashed") +
  labs(title = "KUD95 over Weeks (SpawnSeason = A)",
       x = "Week",
       y = "KUD95") +
  scale_y_continuous(limits = c(0, 15)) +
  theme_minimal()

#W
gam_w <- gam(KUD95 ~ s(Week), data = week_kuds_w[week_kuds_w$SpawnSeason == "W", ], family = Gamma(link = "log"))
summary(gam_w)

week_kuds_w$predicted <- predict(gam_a, newdata = week_kuds_w, type = "response")

plotw <- ggplot(week_kuds_w, aes(x = Week, y = KUD95)) +
  geom_point(col = "blue") +
  geom_line(aes(y = predicted), col = "black", linetype = "dashed") +
  labs(title = "KUD95 over Weeks (SpawnSeason = w)",
       x = "Week",
       y = "KUD95") +
  scale_y_continuous(limits = c(0, 15)) +
  theme_minimal()

grid.arrange(plotss, plota, plotw)

##########################################################################################################
```


```{r}
week_kuds$Week <- as.numeric(week_kuds$Week)

#Model that describes KUD95 over Week by Spawning season
gam_model <- gam(KUD95 ~ s(Week, by = SpawnSeason), data = week_kuds, family = Gamma(link = "log"))
summary(gam_model)

#Make predictions of the model
new_data <- data.frame(Week = rep(seq(min(week_kuds$Week), max(week_kuds$Week), length.out = 100), times = nlevels(week_kuds$SpawnSeason)),
                       SpawnSeason = factor(rep(levels(week_kuds$SpawnSeason), each = 100)))

new_data$predicted_KUD95 <- predict(gam_model, new_data, type = "response")

ggplot(new_data, aes(x = Week, y = predicted_KUD95, color = SpawnSeason)) +
  geom_line() +
  labs(title = "Predicted KUD95 over Weeks by Spawning Season",
       x = "Week",
       y = "Predicted KUD95") +
  scale_y_continuous(limits = c(0, 15)) +
  theme_minimal()

week_kuds$Week <- as.factor(week_kuds$Week)

plot(week_kuds$Week, week_kuds$KUD50)
glm_week1 <- glm(KUD50 ~ Week, data = week_kuds, family=Gamma(link="log"))
with(week_kuds, plot(KUD50 ~ Week, pch = 1, col="deepskyblue"))
seq1 <- levels(week_kuds$Week)
predictweek1 <- predict(glm_week1,newdata=data.frame(Week=seq1), type="response")
lines(seq1, predictweek1, lty=1, col="red")


glmm_spawn <- glmmTMB(KUD95 ~ Spawn + (1|Species), data = week_kuds, family = Gamma(link="log")) 
summary(glmm_spawn)
lm <- lm(KUD95 ~ Spawn * Species, data = week_kuds)
```
